### ISSUE TITLE
Added missing format arguments for Dumper in case of some error cases.

### ISSUE THREAD

**Issue by dranuhl** [eclipse/packager#17]
The org.eclipse.packager.rpm.app.Dumper class contains two cases where it specifies a format string, but lacks the appropriate argument for it, which will lead to an error during the error processing.

For example if the file specified on the command-line can not be found.

Attached public domain patch that I have produced will fix it.

[0001-Added-missing-format-arguments-for-Dumper-in-case-of.patch.txt](https://github.com/eclipse/packager/files/7581608/0001-Added-missing-format-arguments-for-Dumper-in-case-of.patch.txt)

**Comment by ctron** [comment]
@dranuhl thanks for the patch. Unfortunately, for an Eclipse project, I do need a PR and a signed ECA: https://www.eclipse.org/legal/ECA.php

Sure there is way to work around the PR, but not around the ECA. Having a PR however makes it much easier to handle. So I would kindly ask to submit a PR instead.

If you need any help or clarification, feel free to reach out.
