### ISSUE TITLE
RPM builds are not reproducible

### ISSUE THREAD

**Issue by tisoft** [eclipse/packager#18]
RPMs build by the packager are not reproducible.

Following issues have been found:
- Dependency sorting is not stable, if two dependencies are equal in name and version, but differ in their flags, they are sorted differently each time, leading to a different RPM
- ~~Payload order is not stable~~ Caused by the rpm-builder maven plugin

~~There is probably more, will add it to the issue, as soon as I find it.~~ Seems to be the only issue, the rest seems to be caused by the rpm-builder maven plugin

**Comment by ctron** [comment]
I guess what remains is performing a release. Unless there are any concerns, I will go for this, this week. It might take a bit longer, as we probably need a release review this time.

**Comment by tisoft** [comment]
Do you have any new status on the release performing? I would like to get https://github.com/ctron/rpm-builder/issues/60 closed. 😄

**Comment by ctron** [comment]
Yea, the release review was passed this week. I just found no time so far to actually do it … I think Friday is a good day to some side project stuff :grinning:

**Comment by ctron** [comment]
I pushed the release (`0.18.0`). It might take a bit until it is visible on Maven central.

**Comment by ctron** [comment]
It's here: https://repo.maven.apache.org/maven2/org/eclipse/packager/packager/0.18.0/

And thanks again for the contribution!
