### ISSUE TITLE
Maven release appears to be missing JARs

### ISSUE THREAD

**Issue by mikehearn** [eclipse/packager#21]
https://repo1.maven.org/maven2/org/eclipse/packager/packager/0.18.0/

There's a POM but where are the JARs? As a result, importing the library doesn't work.

**Comment by dwalluck** [comment]
It's a modular build. That's just the parent POM.

**Comment by mikehearn** [comment]
Ah, sorry. There are jars but in a different coordinate indeed.

The right coordinates are like this:

    implementation("org.eclipse.packager:packager-rpm:0.18.0")
    implementation("org.eclipse.packager:packager-core:0.18.0")

We went wrong because clicking the badge in the README takes you to the parent pom page, which has a Gradle snippet to copy/paste. But, it doesn't work. I guess Gradle doesn't understand parent poms.

**Comment by dwalluck** [comment]
I am not sure if it's worth changing the link so that it just looks up the group and not the artifact. Then, you'd see the full list of artifacts.

**Comment by mikehearn** [comment]
That could also work, yes.
