### ISSUE TITLE
RPMs created can't be used on an AIX machine

### ISSUE THREAD

**Issue by rohit-lshift** [eclipse/packager#7]
Hello,
I am using this library to create RPMs for a Linux machine and an AIX machine. The AIX machine is somewhat old.

I noticed when I generated the RPMS after this commit: 2ae188015559be3cd831d6634e73575723484b39, I am unable to use the RPMs produced on the AIX box. I get a really unhelpful error:

```bash
root@somemachine:/tmp> rpm -Uvh somerpm.aix7.1.noarch.rpm
error: somerpm.aix7.1.noarch.rpm cannot be installed
``` 

Any help debugging this would be really helpful.

RPM version being used:

```bash
root@somemachine:/tmp> rpm --version
RPM version 3.0.5
```

I am using this library through ctron/rpm-builder

**Comment by dwalluck** [comment]
You're using a version of RPM over 20 years old, but I guess version 3.0.5 has some compatibility with v4 packages. I am responsible for that commit and I don't think it was supposed to change any headers by default. In other words, it added some options, but the default behavior should have remained the same.

Do you think you can produce the exact same RPM using the previous version so that we can compare the two files and see what as changed?

**Comment by rohit-lshift** [comment]
@dwalluck, I know its 20 years old. :(

I can produce RPMs from before and after that commit. 

I tried to use `pkgdiff` to "diff" the two rpms but the tool didn't report any differences.

How else can I check whats different?

Thanks for your help.

**Comment by dwalluck** [comment]
So it did not show any changes in the `Changes In "Requires" Dependencies`? That would have been my first guess. I don't have access to the script producing your packages, but I'll try comparing the RPMs produced by the tests. If you have `hexdump` you could dump both files to compare them byte for byte.

**Comment by rohit-lshift** [comment]
It doesn't show any changes in `Changes In "Requires" Dependencies`. 
<img width="579" alt="Screenshot 2019-11-17 at 20 32 39" src="https://user-images.githubusercontent.com/33258815/69013584-706b6280-0979-11ea-97aa-3c6d692e3a91.png">

The files sizes are different. Before: `1516992`. After `1488742`

**Comment by rohit-lshift** [comment]
Finally found one difference:

Old:

```bash
$ rpm -Kv old.rpm
old.rpm:
    Header SHA1 digest: OK
    MD5 digest: OK
```

New:
```bash
$ rpm -Kv new.rpm
new.rpm:
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    MD5 digest: OK
```

So looks like `Header SHA256 digest` is added by that commit.

**Comment by dwalluck** [comment]
Great, so if you use the current master and remove the line at https://github.com/eclipse/packager/blob/f3addeedef54a0c1aa705450b8f4690f94cb88b1/rpm/src/main/java/org/eclipse/packager/rpm/build/RpmBuilder.java#L790 it should hopefully work for you again. Can you try?

I can make a pull request to make this optional, but I am not sure yet how we should decide to handle it. The API only currently seems to allow you to remove all signature processors, not remove just a single (existing) one. However, you can currently add one if it doesn't already exist. Maybe we should wait for @ctron to comment.

I have had this idea that the builder should take an API compatibility level and then it would enable or disable features automatically based on that. Presumably, you are using https://github.com/ctron/rpm-builder so maybe something should be done here instead to allow this feature to be changed on the fly.

**Comment by dwalluck** [comment]
Oh, I should have read your comment where you said you tried this already.

**Comment by rohit-lshift** [comment]
What surprises me is the file size difference between the two. The new rpm is 28250 bytes less than the old one roughly 1.86%.

**Comment by dwalluck** [comment]
I think that the gzip compression may be responsible for (most) of the size reduction in the new file payload. Before the RPM header indicated `9 = BEST_COMPRESSION`, but it was actually set to `DEFAULT_COMPRESSION` which is somewhat lower.

**Comment by dwalluck** [comment]
The tests use this `Dumper.dumpAll ( in )` to dump the RPM in some readable format.

**Comment by rohit-lshift** [comment]
Thanks. I'll give it a shot. btw, its not the compression. On your suggestion, I changed compression level to `DEFAULT_COMPRESSION` with no effect.

**Comment by rohit-lshift** [comment]
I ran `Dumper.dumpAll` on the two RPMs. The old `PAYLOAD` has `PAYLOAD_FLAGS` whereas the new one doesn't.

**Comment by rohit-lshift** [comment]
No luck. I added the `PAYLOAD_FLAGS` and still no effect.

So with all my changes - old file size: `1516992`. New file size: `1516972`. Getting close.

**Comment by rohit-lshift** [comment]
I've figured it out. `addSignatureProcessor ( SignatureProcessors.md5 () );` needs to be before `addSignatureProcessor ( SignatureProcessors.sha1Header () );`.

🙀

**Comment by dwalluck** [comment]
Unless I am reading the code wrong, I thought the official RPM puts the headers in the order that is it there: SHA256, SHA1, MD5:

https://github.com/rpm-software-management/rpm/blob/d320a1c67ca53496bd190ed6d5586e796c2b19af/lib/signature.c#L112

**Comment by rohit-lshift** [comment]
I created the same rpm for linux and inspected it.

```
$ rpm --version
RPM version 4.15.0
```

When I ran `rpmkeys -Kv name.rpm`, I got.

```bash
   Header SHA256 digest: OK
    Header SHA1 digest: OK
    MD5 digest: OK
```

I don't think I can update the rpm binary on the AIX box as that would be require quite a lot of change in our prod servers as well. 😢

**Comment by dwalluck** [comment]
Does RPM 4.15.0 create RPMs that you can install with RPM 3.0.5?

**Comment by rohit-lshift** [comment]
@dwalluck: What I did was create the RPM for Linux and not AIX. Then I installed it on a Linux box. The underlying packager library was the same.

Hope I am clearer this time around.

**Comment by dwalluck** [comment]
I have not tested it, but I think that upstream RPM has broken backwards compatibility with this change. That is why I asked if someone wanted to build on official RPM 4.x and see if it installs with 3.0.5.

They seem to provide no way to disable SHA256 signatures via macros the way you may be able to disable some other newer features to keep backwards compatibility.

**Comment by ctron** [comment]
@rohit-lshift I created a PR in the Maven Plugin repository, see: https://github.com/ctron/rpm-builder/commit/cb5def3f3011b956b1c3e44330f49d0125c5322b

I would kindly ask you to test, if that works for you, then I would merge the PR and do a new release in a few days.

**Comment by rohit-lshift** [comment]
@ctron: that does indeed work. Thanks!

**Comment by ctron** [comment]
Is it ok to close this issue?

**Comment by rohit-lshift** [comment]
Thanks a lot @ctron!
