### ISSUE TITLE
No longer builds with Java 8

### ISSUE THREAD

**Issue by dwalluck** [eclipse/packager#8]
The commit https://github.com/eclipse/packager/commit/c5fce609c1de5f81bffa3459d8722095737df418 added the `release` flag which causes the build to fail on Java 8 which does not have this flag.

You either have to use Maven profiles or simply replace 

```
<release>${java.release}</release>
```

with

```
<source>${java.source}</source>
<target>${java.source}</target>
```

I also see there is a `${java.source}` defined but not use. I think only one of this or `${java.release}` values is needed.

**Comment by ctron** [comment]
Yes, it no longer builds on Java 8. However it still should run on Java 8. The reason for using the "release" flag was that it will check the use of APIs as well. Eliminating the need for something like the "animal sniffer" (https://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/) plugin.

**Comment by dwalluck** [comment]
Can we provide a build profile, then, to build on 1.8 and have 1.9+ use the release option?

I'm currently using 1.8 so I'd like to not see that ability disappear.

**Comment by ctron** [comment]
Ok, understood. Would it be ok for you to have the 9+ be the default, and the 8 an optional profile?

**Comment by ctron** [comment]
@dwalluck I made a change on master, re-adding Java 8 compilation support. Can you check if that works for you. It looked good on travis.

**Comment by dwalluck** [comment]
@ctron I guess you forgot to push it as I don't see any recent commits, but before you do, you may want to take a look at my attempt https://github.com/eclipse/packager/pull/10.

**Comment by ctron** [comment]
Sorry. I did the change on the RPM plugin :grin:  … merged your PR for the packager.

**Comment by ctron** [comment]
With the release of 0.16.1, we should be able to close this.

**Comment by dwalluck** [comment]
Verified working.
